import {AuthenticationFactory} from '../factories/authenticationFactory';
import {BookingFactory} from '../factories/bookingFactory';
import {AmendPaymentPage} from '../pages/amendPaymentPage';
import {ChangeDatesPage} from '../pages/changeDatesPage';
import {ChangeDatesSummaryPage} from '../pages/changeDatesSummaryPage';
import {ChangeFlightsPage} from '../pages/changeFlightsPage';
import {ChangeNamePage} from '../pages/changeNamePage';
import {ChangeRoomBoardPage} from '../pages/changeRoomBoardPage';
import {ChangeSeatsPage} from '../pages/changeSeatsPage';
import {ChangeSpecialRequestPage} from '../pages/changeSpecialRequestPage';
import {ChangeTransferPage} from '../pages/changeTransferPage';
import {ContactUsPage} from '../pages/contactUsPage';
import {CreateAccountPage} from '../pages/createAccountPage';
import {DualAuthorizationPage} from '../pages/dualAuthorizationPage';
import {HomePage} from '../pages/homePage';
import {LoginPage} from '../pages/loginPage';
import {ManagePage} from '../pages/managePage';
import {SSOLoginPage} from '../pages/ssoLoginPage';
import {TPFindBookingPage} from '../pages/tpFindBookingPage';
import {TradePortalConfirmationPage} from '../pages/tradePortalConfirmationPage';
import {TradePortalFeedbackFormPage} from '../pages/tradePortalFeedbackFormPage';
import {TradePortalLoginPage} from '../pages/tradePortalLoginPage';
import {ViewBookingPage} from '../pages/viewBookingPage';
import {FlightService} from '../services/flightService';
import {WebApiClient} from '../services/webApi/webApiClient';

export interface TestContext {
    amendPaymentPage: AmendPaymentPage;
    authenticationFactory: AuthenticationFactory;
    bookingFactory: BookingFactory;
    changeFlightPage: ChangeFlightsPage;
    changeRoomBoardPage: ChangeRoomBoardPage;
    changeSpecialRequestPage: ChangeSpecialRequestPage;
    changeTransferPage: ChangeTransferPage;
    contactUsPage: ContactUsPage;
    createAccountPage: CreateAccountPage;
    loginPage: LoginPage;
    viewBookingPage: ViewBookingPage;
    webApiClient: WebApiClient;
    ssoLoginPage: SSOLoginPage;
    changeDatesPage: ChangeDatesPage;
    homePage: HomePage;
    dualAuthorizationPage: DualAuthorizationPage;
    tradePortalConfirmationPage: TradePortalConfirmationPage;
    changeDatesSummaryPage: ChangeDatesSummaryPage;
    changeSeatsPage: ChangeSeatsPage;
    changeNamePage: ChangeNamePage;
    managePage: ManagePage;
    tpFindBookingPage: TPFindBookingPage;
    tradePortalLoginPage: TradePortalLoginPage;
    flightService: FlightService;
    tradePortalFeedbackFormPage: TradePortalFeedbackFormPage;
}
